config/routes.rb
Languagelearningexperiment::Application.routes.draw do
  
  root :to => 'iterative_chains#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # match 'iterative_chains/start' => 'iterative_chains#start', :as => 'start'
  # match 'user_entries/training' => 'user_entries#training', :as => 'training'
  
  match '/start' => 'user_entries#start', :as => 'start'
  
  resources :iterative_chains do
    get ':controller(/:action(/:id))'
    resources :user_entries
  end
  
  # get ':controller(/:action(/:id))'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation
end

app/models/iterative_chain.rb
class IterativeChain < ActiveRecord::Base
  attr_accessible :locked
  
  has_many :user_entries, dependent: :destroy
  
end

app/models/user_entry.rb
class UserEntry < ActiveRecord::Base
  attr_accessible :iterative_chain_id, :pairs
  serialize :pairs
  
  belongs_to :iterative_chain
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/iterative_chains_controller.rb
class IterativeChainsController < ApplicationController
  # GET /iterative_chains
  # GET /iterative_chains.json
  def index
    @iterative_chains = IterativeChain.all
  end

  # GET /iterative_chains/1
  # GET /iterative_chains/1.json
  def show
    @iterative_chain = IterativeChain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @iterative_chain }
    end
  end

  # GET /iterative_chains/new
  # GET /iterative_chains/new.json
  def new
    @iterative_chain = IterativeChain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @iterative_chain }
    end
  end

  # GET /iterative_chains/1/edit
  def edit
    @iterative_chain = IterativeChain.find(params[:id])
  end

  # POST /iterative_chains
  # POST /iterative_chains.json
  def create
    @iterative_chain = IterativeChain.new(params[:iterative_chain])

    respond_to do |format|
      if @iterative_chain.save
        format.html { redirect_to @iterative_chain, notice: 'Iterative chain was successfully created.' }
        format.json { render json: @iterative_chain, status: :created, location: @iterative_chain }
      else
        format.html { render action: "new" }
        format.json { render json: @iterative_chain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /iterative_chains/1
  # PUT /iterative_chains/1.json
  def update
    @iterative_chain = IterativeChain.find(params[:id])

    respond_to do |format|
      if @iterative_chain.update_attributes(params[:iterative_chain])
        format.html { redirect_to @iterative_chain, notice: 'Iterative chain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @iterative_chain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iterative_chains/1
  # DELETE /iterative_chains/1.json
  def destroy
    @iterative_chain = IterativeChain.find(params[:id])
    @iterative_chain.destroy

    respond_to do |format|
      format.html { redirect_to iterative_chains_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_entries_controller.rb
class UserEntriesController < ApplicationController
  # GET /user_entries
  # GET /user_entries.json
  def index
    @user_entries = UserEntry.all
  end
  
  
  def start
    @user_entry = UserEntry.new
  end
  
  def pair_with_chain
    
    @iterative_chains = IterativeChain.all
    
    # Find unlocked chains
    @unlocked = @iterative_chains.select { |chain| chain[:locked] == false }
    @chain_id = -1
    
    # Pick the shortest chain
    if @unlocked.empty? != false
      min = @unlocked[0].user_entries.length
      @chain_id = @unlocked[0].id
      
      @unlocked.each_with_index { |chain, index|
        if chain.user_entries.length < min
          min = chain.user_entries.length
          @chain_id = chain.id
        end
      }
    end
    
    # All chains are locked
    if @chain_id == -1
      
    # Shortest unlocked chain has been selected
    # Set a session and lock the chain
    else
      
    end
  end
  
  # Create a new user entry, associated with a free IterativeChain
  def start_create
    # # All chains are locked
    # if @chain_id == -1
    #   flash[:notice] = "Sorry, there are no chains available at this moment. Please try again later."
    #   redirect_to action: :new
    #   
    # # Shortest unlocked chain has been selected
    # # Set a session and lock the chain
    # else
    #   @chain = @iterative_chains.find(@chain_id)
    #   @chain.user_entries.new(params[:user_entry])
    #   @user_entry.save
    #   # Save the user ID in the session so it can be used in
    #   # subsequent requests
    #   session[:current_user_id] = @user_entry.id
    # end
  end
  
  def start_training
  end

  # GET /user_entries/1
  # GET /user_entries/1.json
  def show
    @user_entry = UserEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_entry }
    end
  end

  # POST /user_entries
  # POST /user_entries.json
  def create
    @user_entry = UserEntry.new(params[:user_entry])

    respond_to do |format|
      if @user_entry.save
        format.html { redirect_to @user_entry, notice: 'User entry was successfully created.' }
        format.json { render json: @user_entry, status: :created, location: @user_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @user_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_entries/1
  # PUT /user_entries/1.json
  def update
    @user_entry = UserEntry.find(params[:id])

    respond_to do |format|
      if @user_entry.update_attributes(params[:user_entry])
        format.html { redirect_to @user_entry, notice: 'User entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_entries/1
  # DELETE /user_entries/1.json
  def destroy
    @user_entry = UserEntry.find(params[:id])
    @user_entry.destroy

    respond_to do |format|
      format.html { redirect_to user_entries_url }
      format.json { head :no_content }
    end
  end
  
  # GET Training /user_entries/training
  # GET Training /iterative_chains/:iterative_chain_id/user_entries/training
  def training
    @iterative_chain = IterativeChain.find(params[:iterative_chain_id])
    @user_entry = @iterative_chain.user_entries.last
    @stimuli = @user_entry.pairs
  end
  
  # GET Testing /user_entries/testing
  # GET Testing /iterative_chains/:iterative_chain_id/user_entries/testing
  def testing
    @iterative_chain = IterativeChain.find(params[:iterative_chain_id])
    @last_user_entry = @iterative_chain.user_entries.last
    
    @phones = []
    @sems = []
    # Randomly sort the pairs of stimuli
    @last_user_entry.pairs.each do |pair|
      @phones = @phones.push(pair[:sound])
      @sems = @sems.push(pair[:image])
    end
    @phones = @phones.shuffle
    @sems = @sems.shuffle
    
    @phone_to_sem = false
    if (@iterative_chain.user_entries.size % 2) == 0
      @phone_to_sem = true
    end

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @user_entry }
    # end
  end
  
  # POST Testing /user_entries/testing
  # POST Testing /iterative_chains/:iterative_chain_id/user_entries/testing
  def record
    # respond_to do |format|
    #   if @user_entry.save
    #     format.html { redirect_to @user_entry, notice: 'User entry was successfully created.' }
    #     format.json { render json: @user_entry, status: :created, location: @user_entry }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @user_entry.errors, status: :unprocessable_entity }
    #   end
    # end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/iterative_chains_helper.rb
module IterativeChainsHelper
end

app/helpers/user_entries_helper.rb
module UserEntriesHelper
end

app/views/iterative_chains/_form.html.erb
<%= form_for(@iterative_chain) do |f| %>
  <% if @iterative_chain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iterative_chain.errors.count, "error") %> prohibited this iterative_chain from being saved:</h2>

      <ul>
      <% @iterative_chain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :locked %><br />
    <%= f.check_box :locked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/iterative_chains/edit.html.erb
<h1>Editing iterative_chain</h1>

<%= render 'form' %>

<%= link_to 'Show', @iterative_chain %> |
<%= link_to 'Back', iterative_chains_path %>

app/views/iterative_chains/index.html.erb
<h1>All Iterative Chains and User Entries</h1>

<ul class="iterative-chains">
	<% @iterative_chains.each_with_index do |iterative_chain, index|%>
		<li>
			<div>Iterative Chain # <%= index %></div>
			<% iterative_chain.user_entries.each_with_index do |user_entry, index| %>
			  <div>
			    <div><%= user_entry.pairs %></div>
			    <div><%= user_entry.iterative_chain_id %></div>
			  </div>
			<% end%>
		</li>
	<% end%>
</ul>

app/views/iterative_chains/new.html.erb
<h1>New iterative_chain</h1>

<%= render 'form' %>

<%= link_to 'Back', iterative_chains_path %>

app/views/iterative_chains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Locked:</b>
  <%= @iterative_chain.locked %>
</p>


<%= link_to 'Edit', edit_iterative_chain_path(@iterative_chain) %> |
<%= link_to 'Back', iterative_chains_path %>

app/views/iterative_chains/start.html.erb
<h1>Terms</h1>
<p>Please press the next button to start experiment.</p>
<form >
	<input type="submit" value="Start Experiment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Languagelearningexperiment</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>

app/views/user_entries/_form.html.erb
<%= form_for(@user_entry) do |f| %>
  <% if @user_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_entry.errors.count, "error") %> prohibited this user_entry from being saved:</h2>

      <ul>
      <% @user_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pairs %><br />
    <%= f.text_area :pairs %>
  </div>
  <div class="field">
    <%= f.label :iterative_chain_id %><br />
    <%= f.number_field :iterative_chain_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_entries/index.html.erb
<h1>Listing user_entries</h1>

<table>
  <tr>
    <th>Pairs</th>
    <th>Chain</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_entries.each do |user_entry| %>
  <tr>
    <td><%= user_entry.pairs %></td>
    <td><%= user_entry.iterative_chain_id %></td>
    <td><%= link_to 'Show', user_entry %></td>
    <td><%= link_to 'Edit', edit_user_entry_path(user_entry) %></td>
    <td><%= link_to 'Destroy', user_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User entry', new_user_entry_path %>

app/views/user_entries/instructions.html.erb
<h1>Instructions</h1>
<p>Welcome to this experiment. Please read all instructions carefully before you start the experiment. In this experiment, you will be learning an alien language. In this phase of the experiment, you will see pictures displayed on the computer screen, one at a time. At the same time, you will hear through the speaker the corresponding alien word referring to that picture. Please try to remember as many words and what picture they refer to as you can.</p>
<input type="submit" value="Start Experiment">

app/views/user_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pairs:</b>
  <%= @user_entry.pairs %>
</p>

<p>
  <b>Chain:</b>
  <%= @user_entry.iterative_chain_id %>
</p>


<%= link_to 'Edit', edit_user_entry_path(@user_entry) %> |
<%= link_to 'Back', user_entries_path %>

app/views/user_entries/start.html.erb
<div class="user-entries-start">
	<div>
		<div>Welcome to this experiment. Please read all instructions carefully before you start the experiment. In this experiment, you will be learning an alien language. In this phase of experiment, you will see pictures displayed on the computer screen, one at a time. At the same time, you will hear through the speaker the corresponding alien word referring to that picture. Please try to remember as many words and what picture they refer to as you can.</div>
	</div>
	<%= form_for @user_entry, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
	  <%= f.text_field :title %>
	  <%= f.text_area :body, size: "60x12" %>
	  <%= f.submit "Start" %>
	<% end %>
</div>

app/views/user_entries/start_training.html.erb
<div class="user-entries-start-training">
	<div>
		<div>Click the start button below to start this phase of the experiment</div>
	</div>
	<input class="go-to-training" type="button" value="Start">
</div>

app/views/user_entries/testing.html.erb
<% if @phone_to_sem %>
	<div class="user-entries-testing sem-to-phone">
		<h1>Testing</h1>
		<p>Sem to phone</p>
		<div class='main-stimuli'>
			<% @sems.each_with_index do |sem, index| %>
				<% if index == 0 %>
					<div class='img-wrapper testing show'>
				<% else %>
					<div class='img-wrapper'>
				<% end %>
						<%= image_tag sem + ".jpg" %>
					</div>
			<% end %>
		</div>
		<div class="choices-wrapper">
			<% @phones.each_with_index do |phone, index| %>
				<div class='choice'>
					<div class='audio-wrapper'>
						<input class="play" type="button" value="Play Word"/>
						<%= content_tag(:audio, phone, :controls => "controls") do %>
							<%= content_tag(:source, "", :src => "/assets/" + phone + ".wav") %>
						<% end %>
					</div>
					<input class="audio-input" name="sem_to_phone" type="radio"/>
				</div>
			<% end %>
		</div>
		<input class="next" type="button" value="Next">
	</div>
<% else %>
	<div class="user-entries-testing phone-to-sem">
		<h1>Testing</h1>
		<p>Phone to sem</p>
		<div class='main-stimuli'>
			<input class="play-again" type="button" value="Play Word Again"/>
			<% @phones.each_with_index do |phone, index| %>
				<% if index == 0 %>
					<div class='audio-wrapper testing'>
				<% else %>
					<div class='audio-wrapper'>
				<% end %>
						<%= content_tag(:audio, phone, :controls => "controls") do %>
							<%= content_tag(:source, "", :src => "/assets/" + phone + ".wav") %>
						<% end %>
					</div>
			<% end %>
		</div>
		<div class="choices-wrapper">
			<% @sems.each_with_index do |sem, index| %>
				<div class='choice'>
					<div class='img-wrapper'>
						<%= image_tag sem + ".jpg" %>
					</div>
					<input class="img-input" name="phone_to_sem" type="radio"/>
				</div>
			<% end %>
		</div>
		<input class="next" type="button" value="Next">
	</div>
<% end %>

app/views/user_entries/training.html.erb
<div class='user-entries-training'>
	<h1>Training</h1>
	<p>Please listen to the sound displayed with the image</p>
	<% @stimuli.each_with_index do |stimulus, index| %>
	<div class="training-stimulus" id='<%= "stimuli_" + index.to_s %>'>
		<div class='img-wrapper'>
			<%= image_tag stimulus[:image] + ".jpg" %>
		</div>
		<div class='audio-wrapper'>
			<%= content_tag(:audio, stimulus[:sound], :controls => "controls") do %>
				<%= content_tag(:source, "", :src => "/assets/" + stimulus[:sound] + ".wav") %>
			<% end %>
		</div>
	</div>
	<% end %>
</div>